#! /usr/bin/env bash

chcp.com 65001

echo -e "192.168.0.254로 고정 IP 설정합니다. 엔터를 누르시면 진행하고, IP 충돌 시 여기에 입력하시면 입력하신 IP로 설정됩니다.(예시, 192.168.0.253): "
read CONTINUE
CONTINUE=${CONTINUE:-192.168.0.254}

if [[ ! "$CONTINUE" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];then
  echo 잘못된 IP 설정입니다.
  exit 0
fi

ADDRS=$(netsh interface ip show config | findstr -R "\".*\" 인터페이스에 대한.* IP 주소.*\d*\.\d*\.\d*\.\d*|Configuration for interface.* IP Address.*\d*\.\d*\.\d*\.\d*")

# 순회 인덱스
COUNT=0

# 인터페이스 구성 정보 조회
netsh interface ip show config | findstr -R "\".*\" 인터페이스에 대한.* IP 주소.*\d*\.\d*\.\d*\.\d*|Configuration for interface.* IP Address.*\d*\.\d*\.\d*\.\d*" | while read line; do
  # 구성 정보 상단만 보고 종료
  if [ $COUNT == 4 ]; then
    break
  fi

  # 인터페이스 이름 추출
  if [[ "$line" =~ "Configuration for interface \"Wi-Fi\"" ]]; then
    INTERFACE_NAME=$(echo "$line" | sed 's/Configuration for interface //;s/"//g')
  fi

  # IP 주소 추출
  if [[ $INTERFACE_NAME != "" && "$line" =~ "IP Address" ]]; then
    IP_ADDRESS=$(echo "$line" | sed 's/IP Address\s*: //' | tr -d '[:blank:]')

    # 인터페이스 이름과 IP 주소 출력
    echo "Interface Name: $INTERFACE_NAME"
    echo "IP Address: $IP_ADDRESS"
    echo
  fi

  # 순회 시 인덱스 증가
  COUNT=$(($COUNT + 1))
done

netsh interface ip set address "$INTERFACE_NAME" static $CONTINUE 255.255.255.0 192.168.0.1

echo "고정 IP 설정이 완료되었습니다. 적용된 IP는 $CONTINUE입니다."
read -p "Press any key to continue . . . "